"""Añadir campo category a la tabla Note

Revision ID: 3227570e0346
Revises: 08e098fe93bc
Create Date: 2023-11-24 08:29:28.411880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3227570e0346'
down_revision = '08e098fe93bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
